services:
  underwater-vo:
    build: .
    container_name: underwater_vo
    volumes:
      - ./scripts:/app/scripts
      - ./data:/app/data
      - ./output:/app/output
      - ./notebooks:/app/notebooks
    environment:
      - PYTHONPATH=/opt/ros/noetic/lib/python3/dist-packages:/app:/app/scripts
      - MPLBACKEND=Agg
    network_mode: host
    stdin_open: true
    tty: true
    command: bash -c "source /opt/ros/noetic/setup.bash && bash"